version: "2"

formatters:
  enable:
    # checks if the code and import statements are formatted according to the 'goimports' command'
    - goimports
    - gofmt
    - golines # checks if code is formatted, and fixes long lines
  settings:
    golines:
      # Target maximum line length
      # Default: 100
      max-len: 80
linters:
  settings:
    ireturn:
      allow: [anon, error, empty, stdlib]
    mnd:
      ignored-numbers: ["2", "3", "0.5"]
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - funcorder
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - intrange
    - ireturn
    - lll
    - loggercheck
    - makezero
    - mirror
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - cyclop
    - decorder
    - depguard
    - dogsled
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - goheader
    - gomodguard
    - interfacebloat
    - maintidx
    - misspell
    - musttag
    - nlreturn
    - noinlineerr
    - nolintlint
    - testableexamples
    - varnamelen
    - wsl
    - wsl_v5
