version: 2

before:
  hooks:
    - gzip -f -n -k -9 ./man/{{ .ProjectName }}.1

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE*
      - man/{{ .ProjectName }}.1.gz

nfpms:
  - maintainer: "{{ .Env.MAINTAINER }}"
    homepage: 'https://github.com/asciimoth/version'
    description: Multi-source semantic version management tool
    license: "Apache OR MIT"
    formats:
      - deb
      - rpm
      - archlinux
    section: default
    contents:
      # map the gzipped man page into the package's man directory
      - src: ./man/{{ .ProjectName }}.1.gz
        dst: /usr/share/man/man1/{{ .ProjectName }}.1.gz

signs:
  - artifacts: all
    args: [ "-u", "{{ .Env.DEFAULT_GPG_FPR }}", "--output", "${signature}", "--detach-sign", "${artifact}" ]

release:
  mode: replace

publishers:
  - name: "GH Pages deb/rpm repo"
    cmd: "{{ .Env.MYREPO }}/maintain add {{ abs .ArtifactPath }}"

announce:
  # Requires TELEGRAM_TOKEN env var
  telegram:
    enabled: true
    chat_id: -1002950691807
    message_template: '[{{ mdv2escape .ProjectName }} {{ mdv2escape .Tag }}]({{ mdv2escape .ReleaseURL }}) is out{{ mdv2escape "!" }}'

